// Generated by scripts/generate-reference-index.ts. Do not edit by hand.
import type { ReferenceKind } from "../types/graph";

export type GeneratedReferenceIndexItem = {
  id: string;
  kind: ReferenceKind;
  title: string;
  target: string;
  nodeIds: string[];
  nodeTitles: string[];
  notes: string[];
};

export const generatedReferenceIndex = [
  {
    "id": "ccb-context",
    "kind": "ccb-source-mapping",
    "title": "CCB context mapping",
    "target": ".external/ccb/src/context.ts",
    "nodeIds": [
      "system-prompt",
      "project-rules",
      "memory",
      "skills",
      "compact",
      "context-budget",
      "memory-hygiene"
    ],
    "nodeTitles": [
      "System Prompt",
      "Project Rules",
      "Memory",
      "Skills",
      "Compact",
      "Context Budget",
      "Memory Hygiene"
    ],
    "notes": [
      "Local reading reference only; not committed."
    ]
  },
  {
    "id": "ccb-query",
    "kind": "ccb-source-mapping",
    "title": "CCB query loop mapping",
    "target": ".external/ccb/src/query.ts",
    "nodeIds": [
      "message",
      "agent-loop",
      "model-adapter",
      "tool-result-write-back"
    ],
    "nodeTitles": [
      "Message",
      "Agent Loop",
      "Model Adapter",
      "Tool Result Write-back"
    ],
    "notes": [
      "Local reading reference only; not committed."
    ]
  },
  {
    "id": "ccb-tasks",
    "kind": "ccb-source-mapping",
    "title": "CCB task runtime mapping",
    "target": ".external/ccb/src/tasks/",
    "nodeIds": [
      "todo-write",
      "todo-read",
      "task-state",
      "subagents",
      "background-tasks",
      "worktree-isolation"
    ],
    "nodeTitles": [
      "TodoWrite",
      "TodoRead",
      "Task State",
      "Subagents",
      "Background Tasks",
      "Worktree Isolation"
    ],
    "notes": [
      "Local reading reference only; not committed."
    ]
  },
  {
    "id": "ccb-tool",
    "kind": "ccb-source-mapping",
    "title": "CCB Tool interface mapping",
    "target": ".external/ccb/src/Tool.ts",
    "nodeIds": [
      "tool-use",
      "tool-registry",
      "tool-schema",
      "tool-context",
      "read-file",
      "write-file-list-files",
      "run-shell",
      "permissions",
      "policy-presets",
      "approval-request",
      "approval-store",
      "path-guard",
      "mcp",
      "plugin-loader"
    ],
    "nodeTitles": [
      "Tool Use",
      "Tool Registry",
      "Tool Schema",
      "Tool Context",
      "read_file",
      "write_file / list_files",
      "run_shell",
      "Permissions",
      "Policy Presets",
      "Approval Request",
      "Approval Store",
      "Path Guard",
      "MCP",
      "Plugin Loader"
    ],
    "notes": [
      "Local reading reference only; not committed."
    ]
  },
  {
    "id": "anthropic-messages",
    "kind": "external-link",
    "title": "Anthropic Messages API",
    "target": "https://docs.anthropic.com/en/api/messages",
    "nodeIds": [
      "message",
      "system-prompt",
      "agent-loop",
      "model-adapter"
    ],
    "nodeTitles": [
      "Message",
      "System Prompt",
      "Agent Loop",
      "Model Adapter"
    ],
    "notes": []
  },
  {
    "id": "anthropic-tool-use",
    "kind": "external-link",
    "title": "Anthropic Tool Use overview",
    "target": "https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/overview",
    "nodeIds": [
      "tool-use",
      "tool-result-write-back",
      "tool-registry",
      "tool-schema",
      "tool-context"
    ],
    "nodeTitles": [
      "Tool Use",
      "Tool Result Write-back",
      "Tool Registry",
      "Tool Schema",
      "Tool Context"
    ],
    "notes": []
  },
  {
    "id": "learn-claude-code",
    "kind": "external-link",
    "title": "shareAI-lab/learn-claude-code",
    "target": "https://github.com/shareAI-lab/learn-claude-code",
    "nodeIds": [
      "todo-write",
      "subagents"
    ],
    "nodeTitles": [
      "TodoWrite",
      "Subagents"
    ],
    "notes": []
  },
  {
    "id": "model-context-protocol",
    "kind": "external-link",
    "title": "Model Context Protocol",
    "target": "https://modelcontextprotocol.io/",
    "nodeIds": [
      "mcp",
      "plugin-loader"
    ],
    "nodeTitles": [
      "MCP",
      "Plugin Loader"
    ],
    "notes": []
  },
  {
    "id": "lab-approval-store",
    "kind": "lab-source",
    "title": "Approval store",
    "target": "labs/ts-agent/src/approval-store.ts",
    "nodeIds": [
      "approval-store"
    ],
    "nodeTitles": [
      "Approval Store"
    ],
    "notes": []
  },
  {
    "id": "lab-context",
    "kind": "lab-source",
    "title": "Context builder",
    "target": "labs/ts-agent/src/context.ts",
    "nodeIds": [
      "system-prompt",
      "project-rules",
      "memory",
      "compact",
      "context-budget"
    ],
    "nodeTitles": [
      "System Prompt",
      "Project Rules",
      "Memory",
      "Compact",
      "Context Budget"
    ],
    "notes": []
  },
  {
    "id": "lab-fake-model",
    "kind": "lab-source",
    "title": "Fake model",
    "target": "labs/ts-agent/src/fake-model.ts",
    "nodeIds": [
      "model-adapter"
    ],
    "nodeTitles": [
      "Model Adapter"
    ],
    "notes": []
  },
  {
    "id": "lab-loop",
    "kind": "lab-source",
    "title": "Teaching agent loop",
    "target": "labs/ts-agent/src/loop.ts",
    "nodeIds": [
      "agent-loop",
      "tool-result-write-back"
    ],
    "nodeTitles": [
      "Agent Loop",
      "Tool Result Write-back"
    ],
    "notes": []
  },
  {
    "id": "lab-memory",
    "kind": "lab-source",
    "title": "Memory loader",
    "target": "labs/ts-agent/src/memory.ts",
    "nodeIds": [
      "memory",
      "memory-hygiene"
    ],
    "nodeTitles": [
      "Memory",
      "Memory Hygiene"
    ],
    "notes": []
  },
  {
    "id": "lab-messages",
    "kind": "lab-source",
    "title": "Message types",
    "target": "labs/ts-agent/src/messages.ts",
    "nodeIds": [
      "message",
      "tool-result-write-back"
    ],
    "nodeTitles": [
      "Message",
      "Tool Result Write-back"
    ],
    "notes": []
  },
  {
    "id": "lab-model",
    "kind": "lab-source",
    "title": "Model interface",
    "target": "labs/ts-agent/src/model.ts",
    "nodeIds": [
      "model-adapter"
    ],
    "nodeTitles": [
      "Model Adapter"
    ],
    "notes": []
  },
  {
    "id": "lab-permissions",
    "kind": "lab-source",
    "title": "Permission policy",
    "target": "labs/ts-agent/src/permissions.ts",
    "nodeIds": [
      "run-shell",
      "permissions",
      "policy-presets",
      "approval-request",
      "path-guard"
    ],
    "nodeTitles": [
      "run_shell",
      "Permissions",
      "Policy Presets",
      "Approval Request",
      "Path Guard"
    ],
    "notes": []
  },
  {
    "id": "lab-project-rules",
    "kind": "lab-source",
    "title": "Project rules loader",
    "target": "labs/ts-agent/src/project-rules.ts",
    "nodeIds": [
      "system-prompt",
      "project-rules"
    ],
    "nodeTitles": [
      "System Prompt",
      "Project Rules"
    ],
    "notes": []
  },
  {
    "id": "lab-todo",
    "kind": "lab-source",
    "title": "Todo tools",
    "target": "labs/ts-agent/src/todo.ts",
    "nodeIds": [
      "todo-write",
      "todo-read"
    ],
    "nodeTitles": [
      "TodoWrite",
      "TodoRead"
    ],
    "notes": []
  },
  {
    "id": "lab-tool-context",
    "kind": "lab-source",
    "title": "Tool context formatter",
    "target": "labs/ts-agent/src/tool-context.ts",
    "nodeIds": [
      "tool-context"
    ],
    "nodeTitles": [
      "Tool Context"
    ],
    "notes": []
  },
  {
    "id": "lab-tool-schema",
    "kind": "lab-source",
    "title": "Tool schema",
    "target": "labs/ts-agent/src/tool-schema.ts",
    "nodeIds": [
      "tool-use",
      "tool-schema"
    ],
    "nodeTitles": [
      "Tool Use",
      "Tool Schema"
    ],
    "notes": []
  },
  {
    "id": "lab-tools",
    "kind": "lab-source",
    "title": "Tool registry",
    "target": "labs/ts-agent/src/tools.ts",
    "nodeIds": [
      "tool-use",
      "tool-registry",
      "read-file",
      "write-file-list-files",
      "run-shell",
      "path-guard"
    ],
    "nodeTitles": [
      "Tool Use",
      "Tool Registry",
      "read_file",
      "write_file / list_files",
      "run_shell",
      "Path Guard"
    ],
    "notes": []
  },
  {
    "id": "local-stage-3-checkpoint",
    "kind": "local-doc",
    "title": "Stage 3 Checkpoint",
    "target": "labs/ts-agent/docs/stage-3-checkpoint.md",
    "nodeIds": [
      "agent-loop",
      "todo-write",
      "task-state",
      "demo-commands"
    ],
    "nodeTitles": [
      "Agent Loop",
      "TodoWrite",
      "Task State",
      "Demo Commands"
    ],
    "notes": []
  },
  {
    "id": "local-roadmap",
    "kind": "local-doc",
    "title": "Claude Code Harness 学习路线",
    "target": "learn/00-roadmap.md",
    "nodeIds": [
      "subagents",
      "background-tasks",
      "worktree-isolation",
      "mcp",
      "plugin-loader"
    ],
    "nodeTitles": [
      "Subagents",
      "Background Tasks",
      "Worktree Isolation",
      "MCP",
      "Plugin Loader"
    ],
    "notes": []
  },
  {
    "id": "local-implementation-plan",
    "kind": "local-doc",
    "title": "落地计划",
    "target": "learn/02-implementation-plan.md",
    "nodeIds": [
      "skills",
      "vite-react-shell"
    ],
    "nodeTitles": [
      "Skills",
      "Vite React Shell"
    ],
    "notes": []
  },
  {
    "id": "local-zero-to-one-plan",
    "kind": "local-doc",
    "title": "从 0 到 1 学习计划",
    "target": "learn/03-zero-to-one-plan.md",
    "nodeIds": [
      "bun-runtime"
    ],
    "nodeTitles": [
      "Bun Runtime"
    ],
    "notes": []
  }
] as const satisfies readonly GeneratedReferenceIndexItem[];

export const referenceIndexStats = {
  "totalReferences": 88,
  "uniqueReferences": 25,
  "nodeCount": 34,
  "byKind": {
    "local-doc": 4,
    "lab-source": 13,
    "ccb-source-mapping": 4,
    "external-link": 4
  }
} as const;
