import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { knowledgeNodes } from "../src/data/knowledgeGraph";
import type { ReferenceKind, SourceReference } from "../src/types/graph";

type ReferenceIndexItem = {
  id: string;
  kind: ReferenceKind;
  title: string;
  target: string;
  nodeIds: string[];
  nodeTitles: string[];
  notes: string[];
};

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDir, "../src/data/generatedReferenceIndex.ts");

const referenceGroups = [
  { key: "labFiles", source: (node: (typeof knowledgeNodes)[number]) => node.labFiles },
  { key: "ccbMappings", source: (node: (typeof knowledgeNodes)[number]) => node.ccbMappings },
  { key: "externalLinks", source: (node: (typeof knowledgeNodes)[number]) => node.externalLinks },
] as const;

const byKind: Record<ReferenceKind, number> = {
  "local-doc": 0,
  "lab-source": 0,
  "ccb-source-mapping": 0,
  "external-link": 0,
};

const indexByKey = new Map<string, ReferenceIndexItem>();
let totalReferences = 0;

function addReference(node: (typeof knowledgeNodes)[number], reference: SourceReference) {
  totalReferences += 1;
  const key = `${reference.kind}:${reference.target}`;
  const existing = indexByKey.get(key);

  if (existing) {
    existing.nodeIds.push(node.id);
    existing.nodeTitles.push(node.title);
    if (reference.note && !existing.notes.includes(reference.note)) {
      existing.notes.push(reference.note);
    }
    return;
  }

  indexByKey.set(key, {
    id: reference.id,
    kind: reference.kind,
    title: reference.title,
    target: reference.target,
    nodeIds: [node.id],
    nodeTitles: [node.title],
    notes: reference.note ? [reference.note] : [],
  });
}

for (const node of knowledgeNodes) {
  for (const group of referenceGroups) {
    for (const reference of group.source(node)) {
      addReference(node, reference);
    }
  }
}

const generatedReferenceIndex = Array.from(indexByKey.values()).sort((a, b) => {
  const kindOrder = a.kind.localeCompare(b.kind);
  if (kindOrder !== 0) return kindOrder;
  return a.target.localeCompare(b.target);
});

for (const item of generatedReferenceIndex) {
  byKind[item.kind] += 1;
}

const fileContent = `// Generated by scripts/generate-reference-index.ts. Do not edit by hand.
import type { ReferenceKind } from "../types/graph";

export type GeneratedReferenceIndexItem = {
  id: string;
  kind: ReferenceKind;
  title: string;
  target: string;
  nodeIds: string[];
  nodeTitles: string[];
  notes: string[];
};

export const generatedReferenceIndex = ${JSON.stringify(generatedReferenceIndex, null, 2)} as const satisfies readonly GeneratedReferenceIndexItem[];

export const referenceIndexStats = ${JSON.stringify(
  {
    totalReferences,
    uniqueReferences: generatedReferenceIndex.length,
    nodeCount: knowledgeNodes.length,
    byKind,
  },
  null,
  2,
)} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, fileContent, "utf8");
console.log(`Generated ${generatedReferenceIndex.length} reference index items.`);
